# Generated by Django 4.2.7 on 2026-05-22 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feereceipt',
            old_name='amount_paid',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='feereceipt',
            old_name='created_at',
            new_name='date_paid',
        ),
        migrations.AlterUniqueTogether(
            name='examrecord',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='classstream',
            name='class_teacher',
        ),
        migrations.RemoveField(
            model_name='feeinvoice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feeinvoice',
            name='term',
        ),
        migrations.RemoveField(
            model_name='feeinvoice',
            name='year',
        ),
        migrations.RemoveField(
            model_name='feereceipt',
            name='payment_channel',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_class_teacher',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='tsc_number',
        ),
        migrations.AddField(
            model_name='classstream',
            name='capacity',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='classstream',
            name='room_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='date_issued',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feereceipt',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.feeinvoice'),
        ),
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('O+', 'O Positive'), ('O-', 'O Negative'), ('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('AB+', 'AB Positive')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_admission',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Boy'), ('F', 'Girl')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(default='Guardian Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_relation',
            field=models.CharField(default='Parent', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='known_allergies',
            field=models.TextField(blank=True, default='None Registered', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_conditions',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='passport_photo_url',
            field=models.URLField(blank=True, default='https://images.unsplash.com/photo-1597545558260-2dc35779abb7?q=80&w=200&auto=format&fit=crop', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active Learner'), ('TRANSFERRED', 'Transferred Out'), ('GRADUATED', 'Alumni / Graduated')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='employee_number',
            field=models.CharField(default='Guardian Unknown', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.subject'),
        ),
        migrations.AlterField(
            model_name='classstream',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='classstream',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='cat_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='cat_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='final_exam',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.student'),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.subject'),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='term',
            field=models.CharField(default='TERM_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='feeinvoice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending Verification'), ('FAILED', 'Failed')], default='COMPLETED', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.classstream'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DisciplineReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reported', models.DateField(auto_now_add=True)),
                ('infraction_details', models.TextField()),
                ('severity', models.CharField(choices=[('MINOR', 'Minor Infraction'), ('MEDIUM', 'Requires Guidance'), ('SEVERE', 'Suspension / Board Action')], default='MINOR', max_length=15)),
                ('action_taken', models.CharField(default='Verbal Warning Given', max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_logs', to='finance.student')),
            ],
        ),
        migrations.RemoveField(
            model_name='examrecord',
            name='created_at',
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_present', models.BooleanField(default=True)),
                ('remarks', models.CharField(blank=True, max_length=150, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='finance.student')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
    ]
