# Generated by Django 4.2.7 on 2026-05-22 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0002_rename_amount_paid_feereceipt_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=30, unique=True)),
                ('role_designation', models.CharField(choices=[('PRINCIPAL', 'School Principal'), ('TEACHER', 'Class Teacher'), ('ACCOUNTANT', 'Bursar / Accountant'), ('SUPPORT', 'Support Staff')], default='TEACHER', max_length=20)),
                ('phone_line', models.CharField(default='0700000000', max_length=15)),
                ('specialization', models.CharField(default='Mathematics / Physics', max_length=100)),
                ('base_salary_kes', models.DecimalField(decimal_places=2, default=45000.0, max_digits=10)),
                ('current_status', models.CharField(choices=[('ACTIVE', 'Active duty'), ('ON_LEAVE', 'On Sanctioned Leave'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=15)),
                ('performance_score', models.IntegerField(default=85)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimetableAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_title', models.CharField(max_length=50)),
                ('weekday', models.CharField(default='Monday', max_length=15)),
                ('time_slot', models.CharField(default='08:00 AM - 08:40 AM', max_length=20)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_taught', to='finance.staffprofile')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.classstream')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_reason', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_approved', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='finance.staffprofile')),
            ],
        ),
    ]
