# Generated by Django 4.2.7 on 2026-05-22 17:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_staffprofile_timetableallocation_leaveapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('ON_LEAVE', 'Sanctioned Leave')], default='PRESENT', max_length=15)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendance', to='finance.staffprofile')),
            ],
            options={
                'unique_together': {('staff', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StudentAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late with Excuse')], default='PRESENT', max_length=15)),
                ('verification_method', models.CharField(default='BIOMETRIC_SCAN', max_length=30)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_history', to='finance.student')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
    ]
