# Generated by Django 4.2.7 on 2026-05-22 20:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_teacherattendancerecord_studentattendancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('announcement_body', models.TextField()),
                ('target_audience', models.CharField(choices=[('ALL_PARENTS', 'All Parents'), ('FORM_1', 'Form 1 Stream Blocks Only'), ('FORM_2', 'Form 2 Stream Blocks Only')], default='ALL_PARENTS', max_length=20)),
                ('date_published', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('task_instructions', models.TextField()),
                ('date_given', models.DateField(default=django.utils.timezone.now)),
                ('submission_deadline', models.DateField()),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='finance.classstream')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.subject')),
            ],
        ),
    ]
