# Generated by Django 4.2.7 on 2026-05-22 20:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_schoolannouncement_homeworkassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('serial_or_isbn', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('TEXTBOOKS', 'Textbook Inventory'), ('LAB_EQUIP', 'Computer & Lab Equipment'), ('FURNITURE', 'School Furniture Property'), ('STORES', 'General Store Supplies')], max_length=20)),
                ('total_quantity', models.PositiveIntegerField(default=1)),
                ('available_quantity', models.PositiveIntegerField(default=1)),
                ('assigned_location', models.CharField(help_text='e.g., Science Lab B, Form 2 Alpha Room', max_length=100)),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Operational / Active'), ('UNDER_REPAIR', 'Under Maintenance'), ('DECOMMISSIONED', 'Decommissioned / Written Off')], default='OPERATIONAL', max_length=20)),
                ('last_audited_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AssetMaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_reported', models.TextField()),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('cost_incurred_kes', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_logged', models.DateField(default=django.utils.timezone.now)),
                ('is_resolved', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_history', to='finance.schoolasset')),
            ],
        ),
    ]
