# Generated by Django 4.2.7 on 2026-06-09 21:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_timetableslot_lessonplan_learningmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feereceipt',
            name='date_issued',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='feereceipt',
            name='description',
            field=models.CharField(default='School Fees Payment', max_length=255),
        ),
        migrations.AddField(
            model_name='studentattendancerecord',
            name='is_present',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentattendancerecord',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assetmaintenancelog',
            name='cost_incurred_kes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='feeinvoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='base_salary_kes',
            field=models.DecimalField(decimal_places=2, default=45000.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
