# Generated by Django 4.2.7 on 2026-07-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_add_all_students_notice_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='feereceipt',
            name='term',
            field=models.CharField(choices=[('TERM_1', 'Term 1'), ('TERM_2', 'Term 2'), ('TERM_3', 'Term 3')], default='TERM_1', max_length=10),
        ),
    ]
