# Generated by Django 4.2.7 on 2026-07-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_feereceipt_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
